# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

1.19.2


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


In [29]:
z = np.zeros((10,10))
print('%d bytes'%(z.size*z.itemsize))
print('배열에 저장되어 있는 요소의 메모리 사이즈는 size로 알 수 있다.',z.size)
print('한 바이트가 8비트',z.itemsize)
print(z.size*z.itemsize)
print(z.dtype)

800 bytes
배열에 저장되어 있는 요소의 메모리 사이즈는 size로 알 수 있다. 100
한 바이트가 8비트 8
800
float64


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [35]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [4]:
np.lookfor('add')

Search results for 'add'
------------------------
numpy.add
    Add arguments element-wise.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.add_newdoc
    Add documentation to an existing object, typically one defined in C
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.ma.add
    Add arguments element-wise.
numpy.add_docstring
    Add a docstring to a built-in obj if possible.
numpy.quantile
    Compute the q-th quantile of the data along the specified axis.
numpy.deprecate
    Issues a DeprecationWarning, adds warning to `old_name`'s
numpy._add_newdoc_ufunc
    Replace the docstring for a ufunc with new_docstring.
numpy.binary_repr
    Return the binary representation of the input number as a string.
numpy.ma.ids
    ids(self)
numpy.fft.test
    Pytest test runner.
numpy.ma.append
    Append values to the end of an array.
numpy.bytes0.ljust
    Return a left-justified string of length width.
numpy.bytes0.rju

In [34]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [40]:
ten = np.zeros(10)
ten[4] = 1
ten

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [41]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [44]:
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [45]:
answer(7)

Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [46]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [47]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [54]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [61]:
temp = []
z = np.array([1,2,0,0,4,0])
def non_zero(i):
    return [i for i in z if i!=0]
#for i in z:
 #   if i != 0:
  #      temp.append(i)
#temp

0

In [62]:
non_zero([1,2,0,0,4,0])

[1, 2, 4]

In [63]:
answer(10)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)


In [64]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
z = np.zeros([3,3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
answer(11)

Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
z = np.empty([3,3,3])
z

array([[[0.0e+000, 0.0e+000, 8.9e-323],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 5.4e-323, 0.0e+000]],

       [[0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000]]])

In [20]:
z = np.random.random((3,3,3))
z

array([[[0.22599553, 0.30415374, 0.71499388],
        [0.72409148, 0.01867644, 0.2858131 ],
        [0.58048634, 0.93078663, 0.3389969 ]],

       [[0.12008312, 0.51627271, 0.69920706],
        [0.29864068, 0.86160962, 0.9058072 ],
        [0.76858325, 0.26123164, 0.9384556 ]],

       [[0.93864246, 0.74504455, 0.91073504],
        [0.23722471, 0.49496735, 0.80987834],
        [0.95456578, 0.63748325, 0.91084975]]])

In [18]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


### random 정리
* np.random.randint(시작,n-1) : 균일분포 정수 난수 1개 생성 
* np.random.rand (m,n) : 0부터 1사이의 균일분포 난수 matrix array 생성
* np.random.randn (m,n) : 정규분포 난수 matrix array 생성 

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
z = np.random.rand(10,10)
print(z)
print(z.max(),z.min())

[[0.15994411 0.56101652 0.44617561 0.85529903 0.91118062 0.87656479
  0.96542923 0.20231131 0.72637586 0.57131802]
 [0.58392733 0.4567219  0.58211084 0.06774828 0.00595052 0.46801175
  0.79022774 0.92294886 0.7202414  0.12593103]
 [0.71909247 0.61549427 0.3867184  0.78521404 0.10134406 0.40293787
  0.74239668 0.01243381 0.92818267 0.46022349]
 [0.06962502 0.90993087 0.1233045  0.89478166 0.20506002 0.93198879
  0.49792914 0.36000406 0.16087119 0.72637597]
 [0.83527485 0.3188789  0.97806536 0.47271119 0.5661444  0.14668441
  0.09974442 0.08651713 0.75301383 0.7422893 ]
 [0.31550636 0.84531443 0.53454666 0.83257035 0.18603398 0.27595303
  0.58305759 0.92995146 0.0572954  0.81829735]
 [0.16462297 0.43970611 0.36652076 0.06577879 0.78780888 0.51238806
  0.1768385  0.52083122 0.59100906 0.44453861]
 [0.14300801 0.96126411 0.41776978 0.13002514 0.65099308 0.5879054
  0.25473751 0.28743283 0.80527886 0.05620763]
 [0.27819169 0.93671139 0.83840657 0.90817385 0.59461709 0.77350132
  0.34409999 

In [32]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [47]:
z = np.random.rand(5,6)
print(z,z.mean())

[[0.36878243 0.28281236 0.24179872 0.87135192 0.36709439 0.88803578]
 [0.94987866 0.8727589  0.37204537 0.64585682 0.43269054 0.73060042]
 [0.69894476 0.43026839 0.40387179 0.60110606 0.64888551 0.11407952]
 [0.70535109 0.35972907 0.42292638 0.31354217 0.56830605 0.03356502]
 [0.97684007 0.97058921 0.28227265 0.65782075 0.77708599 0.94549501]] 0.5644795265899102


In [46]:
z = np.random.random(30)
print(z,z.mean())

[0.38773996 0.81652786 0.22931971 0.66511642 0.57560745 0.079372
 0.04232202 0.8570225  0.14754214 0.10307771 0.10634875 0.29325156
 0.53011683 0.86632552 0.86878375 0.3565033  0.09812746 0.43822729
 0.94748623 0.04159502 0.31084756 0.78228691 0.79551015 0.85258065
 0.54389106 0.59062857 0.13910797 0.03472366 0.15525958 0.75691947] 0.4470723012356718


In [45]:
answer(14)

Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [50]:
z = np.eye(3,4, k = -1)
z

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [57]:
answer(15)

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


In [4]:
z = np.ones((10,10))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [7]:
z = np.zeros_like(z)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


In [9]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set ([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
z = np.diag(1+np.arange(4),k = 0)
z

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [3]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [32]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [33]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


In [42]:
z = np.random.random((5,5))
print(z)
print(np.mean(z))
print(np.std(z))
print((1-np.mean(z))/np.std(z)) # z-score equation

[[0.11458676 0.47534847 0.033433   0.17140612 0.76985571]
 [0.12737067 0.73782781 0.02386977 0.98956593 0.72701419]
 [0.34231094 0.61839352 0.59317414 0.45081468 0.93510278]
 [0.31586189 0.93558196 0.66179725 0.32179451 0.86535016]
 [0.5213169  0.3607197  0.164836   0.89617833 0.01214792]]
0.48662636400736586
0.31228085981062875
1.6439484517365257


In [51]:
# cf Euclidean distance
def euclidean_distance(pt1,pt2):
    distance = 0
    for i in range(len(pt1)):
        distance += (pt1[i] - pt2[i])**2
    return distance ** 0.5 

In [55]:
#print(euclidean_distance([0,0],[3,4]))
pt1 = [0,0]
pt2 = [3,4]
print(euclidean_distance(pt1,pt2))
print(pt1[0],pt2[0],pt1[1],pt2[1])

5.0
0 3 0 4


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [30]:
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [6]:
answer(24)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


In [8]:
a = np.dot(np.ones((5,3)),np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [9]:
np.array([1,2,3])*np.array([4,5,6])

array([ 4, 10, 18])

In [10]:
np.dot(np.array([1,2,3]),np.array([4,5,6]))

32

In [13]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [14]:
a@b

array([[19, 22],
       [43, 50]])

In [15]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [29]:
a = np.arange(1,13).reshape(3,2,2)

b = np.arange(12,24).reshape(2,2,3)
print(a)
print(b)
print(np.dot(a,b))
print(np.dot(a,b).shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
[[[[ 42  45  48]
   [ 60  63  66]]

  [[ 96 103 110]
   [138 145 152]]]


 [[[150 161 172]
   [216 227 238]]

  [[204 219 234]
   [294 309 324]]]


 [[[258 277 296]
   [372 391 410]]

  [[312 335 358]
   [450 473 496]]]]
(3, 2, 2, 3)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [33]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


In [35]:
a = np.arange(11)
a[(3<a)& (a <8)]*= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [36]:

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [37]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [46]:
hint(26)

hint: np.sum


10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [47]:
answer(27)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [53]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-53-6caa14b62dca>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0)/np.array(0))
<ipython-input-53-6caa14b62dca>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [54]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [64]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))
# intersect1d

[1 3 6 8 9]


In [59]:
answer(30)

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)