# python

In [49]:
%%writefile pd_sample/gosu2.txt
hello
안녕

Overwriting pd_sample/gosu2.txt


In [50]:
a = open('pd_sample/gosu2.txt','wb')

In [52]:
a.write(b'hello')

5

In [54]:
a.close()

In [55]:
b = open('pd_sample/gosu2.txt')

In [58]:
next(b)

'hello'

In [59]:
b.close()

## 일반적으로 with 방법 이용 

In [72]:
with open('pd_sample/gosu2.txt','wb') as c:
    c.write(b'aaa')
    c.write(b'bbb')

In [70]:
with open('pd_sample/gosu2.txt','r') as f:
    data = f.read()

In [71]:
data

'aaabbb'

# numpy
* numpy 자체적으로 저장과 불러오는 기능 제공

In [75]:
import numpy as np

In [78]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

numpy의 데이터를 파일에 저장 .npy 포맷으로 저장됨 np.save ('파일이름',데이터)

In [80]:
np.save('pd_sample/t',a)

numpy의 파일을 읽어온다

In [83]:
b = np.load('pd_sample/t.npy') # 확장자를 줘서 읽어와야함 txt npy etc

In [84]:
b

array([0, 1, 2, 3, 4])

savez는 array를 여러개 저장할 수 있다.<br>
확장자는 자동으로 .npz가 붙음

In [85]:
b = np.array([1,2,3,4,5])
c = np.array([6,7,8,9,10])

In [86]:
np.savez('pd_sample/s',b,c)

In [87]:
d = np.load('pd_sample/s.npz')

In [92]:
d

dictionary 방식으로 저장된 객체를 가져올 수 있다.

In [94]:
d.files # dictionary 방식으로 불러와야함

['arr_0', 'arr_1']

In [95]:
d['arr_0'] # 이름이 이렇게 저장되어 있음

array([1, 2, 3, 4, 5])

In [96]:
d['arr_1']

array([ 6,  7,  8,  9, 10])

numpy로 텍스트 파일 읽어오기

In [100]:
# loadtxt()는 기본 리턴타입이 float이기때문에 구분자를 지정하지 않으면 str으로 취급 
np.loadtxt('num_test.txt',delimiter =",") # delimiter 구분자

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

# pandas

In [101]:
import pandas as pd

In [104]:
a = pd.read_csv('num_test.txt',header = None)

In [105]:
a

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10