# python

In [49]:
%%writefile pd_sample/gosu2.txt
hello
안녕

Overwriting pd_sample/gosu2.txt


In [50]:
a = open('pd_sample/gosu2.txt','wb')

In [52]:
a.write(b'hello')

5

In [54]:
a.close()

In [55]:
b = open('pd_sample/gosu2.txt')

In [58]:
next(b)

'hello'

In [59]:
b.close()

## 일반적으로 with 방법 이용 

In [72]:
with open('pd_sample/gosu2.txt','wb') as c:
    c.write(b'aaa')
    c.write(b'bbb')

In [70]:
with open('pd_sample/gosu2.txt','r') as f:
    data = f.read()

In [71]:
data

'aaabbb'

# numpy
* numpy 자체적으로 저장과 불러오는 기능 제공

In [75]:
import numpy as np

In [78]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

numpy의 데이터를 파일에 저장 .npy 포맷으로 저장됨 np.save ('파일이름',데이터)

In [80]:
np.save('pd_sample/t',a)

numpy의 파일을 읽어온다

In [83]:
b = np.load('pd_sample/t.npy') # 확장자를 줘서 읽어와야함 txt npy etc

In [84]:
b

array([0, 1, 2, 3, 4])

savez는 array를 여러개 저장할 수 있다.<br>
확장자는 자동으로 .npz가 붙음

In [85]:
b = np.array([1,2,3,4,5])
c = np.array([6,7,8,9,10])

In [86]:
np.savez('pd_sample/s',b,c)

In [87]:
d = np.load('pd_sample/s.npz')

In [92]:
d

dictionary 방식으로 저장된 객체를 가져올 수 있다.

In [94]:
d.files # dictionary 방식으로 불러와야함

['arr_0', 'arr_1']

In [95]:
d['arr_0'] # 이름이 이렇게 저장되어 있음

array([1, 2, 3, 4, 5])

In [96]:
d['arr_1']

array([ 6,  7,  8,  9, 10])

numpy로 텍스트 파일 읽어오기

In [100]:
# loadtxt()는 기본 리턴타입이 float이기때문에 구분자를 지정하지 않으면 str으로 취급 
np.loadtxt('num_test.txt',delimiter =",") # delimiter 구분자

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

# pandas

In [101]:
import pandas as pd

In [104]:
a = pd.read_csv('num_test.txt',header = None)

In [105]:
a

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [106]:
type(a)

pandas.core.frame.DataFrame

In [107]:
a.to_csv('pd_sample/num2.csv',sep = ',') # column명도 같이 저장됨

In [108]:
a.describe() # descriptive data 정보

0         1         2         3          4
count  2.000000  2.000000  2.000000  2.000000   2.000000
mean   3.500000  4.500000  5.500000  6.500000   7.500000
std    3.535534  3.535534  3.535534  3.535534   3.535534
min    1.000000  2.000000  3.000000  4.000000   5.000000
25%    2.250000  3.250000  4.250000  5.250000   6.250000
50%    3.500000  4.500000  5.500000  6.500000   7.500000
75%    4.750000  5.750000  6.750000  7.750000   8.750000
max    6.000000  7.000000  8.000000  9.000000  10.000000

In [111]:
a.describe().T # transpose로 행과 열 바꾸기 

count  mean       std  min   25%  50%   75%   max
0    2.0   3.5  3.535534  1.0  2.25  3.5  4.75   6.0
1    2.0   4.5  3.535534  2.0  3.25  4.5  5.75   7.0
2    2.0   5.5  3.535534  3.0  4.25  5.5  6.75   8.0
3    2.0   6.5  3.535534  4.0  5.25  6.5  7.75   9.0
4    2.0   7.5  3.535534  5.0  6.25  7.5  8.75  10.0

In [114]:
data = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [115]:
# pandas는 numpy 기반이라서 Numpy기능을 사용할 수 있다
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [116]:
data.describe(include = ['float64','object']) # object(str)도 추가가 되지만 값이 없으므로 nan으로 나옴

total_bill         tip   sex smoker  day    time
count   244.000000  244.000000   244    244  244     244
unique         NaN         NaN     2      2    4       2
top            NaN         NaN  Male     No  Sat  Dinner
freq           NaN         NaN   157    151   87     176
mean     19.785943    2.998279   NaN    NaN  NaN     NaN
std       8.902412    1.383638   NaN    NaN  NaN     NaN
min       3.070000    1.000000   NaN    NaN  NaN     NaN
25%      13.347500    2.000000   NaN    NaN  NaN     NaN
50%      17.795000    2.900000   NaN    NaN  NaN     NaN
75%      24.127500    3.562500   NaN    NaN  NaN     NaN
max      50.810000   10.000000   NaN    NaN  NaN     NaN

In [120]:
data.describe(include = 'O') # 이렇게도 가져올 수 있음 

sex smoker  day    time
count    244    244  244     244
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [121]:
data.describe(include = np.number)

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [122]:
data.describe(include = "all")

total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [127]:
data['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [128]:
data['day'].values.size

244

In [132]:
data['day'].value_counts(ascending = True)

Fri     19
Thur    62
Sun     76
Sat     87
Name: day, dtype: int64

In [134]:
data['day'].value_counts(normalize = True) # returing proportion

Sat     0.356557
Sun     0.311475
Thur    0.254098
Fri     0.077869
Name: day, dtype: float64

In [136]:
data['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [137]:
data['sex'].value_counts(normalize = True)

Male      0.643443
Female    0.356557
Name: sex, dtype: float64

In [139]:
data['size'].value_counts(normalize = True)

2    0.639344
3    0.155738
4    0.151639
5    0.020492
6    0.016393
1    0.016393
Name: size, dtype: float64

In [140]:
data.value_counts()

total_bill  tip    sex     smoker  day   time    size
13.00       2.00   Female  Yes     Thur  Lunch   2       2
50.81       10.00  Male    Yes     Sat   Dinner  3       1
14.52       2.00   Female  No      Thur  Lunch   2       1
15.69       1.50   Male    Yes     Sun   Dinner  2       1
15.53       3.00   Male    Yes     Sat   Dinner  2       1
                                                        ..
20.76       2.24   Male    No      Sun   Dinner  2       1
20.69       5.00   Male    No      Sun   Dinner  5       1
            2.45   Female  No      Sat   Dinner  4       1
20.65       3.35   Male    No      Sat   Dinner  3       1
3.07        1.00   Female  Yes     Sat   Dinner  1       1
Length: 243, dtype: int64

In [142]:
a = data[(data['day'] == 'Sun')|(data['day'] == 'Sat')]

In [144]:
a.value_counts()

total_bill  tip    sex     smoker  day  time    size
50.81       10.00  Male    Yes     Sat  Dinner  3       1
14.48       2.00   Male    Yes     Sun  Dinner  2       1
16.45       2.47   Female  No      Sat  Dinner  2       1
16.31       2.00   Male    No      Sat  Dinner  3       1
16.29       3.71   Male    No      Sun  Dinner  3       1
                                                       ..
22.67       2.00   Male    Yes     Sat  Dinner  2       1
22.42       3.48   Female  Yes     Sat  Dinner  2       1
22.23       5.00   Male    No      Sun  Dinner  2       1
22.12       2.88   Female  Yes     Sat  Dinner  2       1
3.07        1.00   Female  Yes     Sat  Dinner  1       1
Length: 163, dtype: int64

In [146]:
# 같은 컬럼에 있는 값을 가지고 검색할 때 isin()사용할 수 있다.
b = data.isin({'Sun','Sat'})

In [149]:
b.value_counts()

total_bill  tip    sex    smoker  day    time   size 
False       False  False  False   True   False  False    163
                                  False  False  False     81
dtype: int64

### where

In [151]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [152]:
# where의 인자는 조건이다
# 조건만 넣을 경우 True의 위치를 알려준다
np.where(a>3)

(array([3]),)

In [154]:
np.where(a>3,0,100) # 3이상일 경우 100으로 return 이외는 0으로 return

array([100, 100, 100,   0])