In [1]:
import numpy as np

In [6]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [8]:
a[0][0:3]

array([0, 1, 2])

In [10]:
a[0] # 2차원에서 1차원

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
a[[0]] # 2차원그대로

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [22]:
a = np.arange(24).reshape(3,4,2)
b = np.arange(12).reshape(2,2,3)

In [23]:
np.dot(a,b)

array([[[[  3,   4,   5],
         [  9,  10,  11]],

        [[  9,  14,  19],
         [ 39,  44,  49]],

        [[ 15,  24,  33],
         [ 69,  78,  87]],

        [[ 21,  34,  47],
         [ 99, 112, 125]]],


       [[[ 27,  44,  61],
         [129, 146, 163]],

        [[ 33,  54,  75],
         [159, 180, 201]],

        [[ 39,  64,  89],
         [189, 214, 239]],

        [[ 45,  74, 103],
         [219, 248, 277]]],


       [[[ 51,  84, 117],
         [249, 282, 315]],

        [[ 57,  94, 131],
         [279, 316, 353]],

        [[ 63, 104, 145],
         [309, 350, 391]],

        [[ 69, 114, 159],
         [339, 384, 429]]]])

In [27]:
print(b)
np.sum(b, axis = 0)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([[ 6,  8, 10],
       [12, 14, 16]])

In [28]:
print(a)
np.sum(a,axis = 0)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


array([[24, 27],
       [30, 33],
       [36, 39],
       [42, 45]])

In [29]:
print(b)
np.sum(b,axis = 1)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([[ 3,  5,  7],
       [15, 17, 19]])

In [30]:
print(a)
np.sum(a,axis = 1)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


array([[12, 16],
       [44, 48],
       [76, 80]])

In [35]:
print(b)
np.sum(b, axis = 2)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


array([[ 3, 12],
       [21, 30]])

In [34]:
print(a)
np.sum(a,axis = 2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


array([[ 1,  5,  9, 13],
       [17, 21, 25, 29],
       [33, 37, 41, 45]])

In [43]:
print(b)
print(b.shape)
b.reshape(2,-1,6)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]]])

In [63]:
a = np.arange(12).reshape(3,4) # reshape를 통해 1차원을 2차원으로 확장
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [62]:
print(np.stack((a,))) # stack을 통해 2차원을 3차원으로 확장 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [65]:
print(a[np.newaxis]) # newaxis를 통해 2차원을 3차원으로 확장 


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [66]:
print(a[np.newaxis].shape)

(1, 3, 4)
